### ISSUE TITLE
Running tasks

### ISSUE THREAD

**Issue by brian-slate** [webrain/grunt-wordpress-deploy#15]
The example gruntfile in the readme runs "wordpressdeploy" which results in:
Warning: Task "wordpressdeploy" not found. Use --force to continue.

I can run the built-in tasks like "grunt push_files --target=staging", but how should they be incorporated into the default task? Maybe a noob question :)

Thanks!

**Comment by davidthou** [comment]
Discussion moved here:  https://github.com/webrain/grunt-wordpress-deploy/issues/16
