### ISSUE TITLE
How to update Wordpress through this grunt plugin?

### ISSUE THREAD

**Issue by binarykitchen** [webrain/grunt-wordpress-deploy#21]
Awesome, this plugin comes in very handy. But tell me, how do you update the core WP code with this plugin?

I mean, do you download the core WP code from the site into the same directory and let the grunt task deploy the update to the site? Or do you generate/update it with Yeoman https://github.com/romainberger/yeoman-wordpress#configuration ?

**Comment by Grawl** [comment]
You can install/update WP from [WordPress](https://github.com/WordPress/WordPress) Github repository with `bower install wordpress` and running/deploying it from `bower_components/wordpress/`.

**Comment by binarykitchen** [comment]
Thanks!

**Comment by Grawl** [comment]
Glad to help.
