### ISSUE TITLE
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)

### ISSUE THREAD

**Issue by chriswinch** [webrain/grunt-wordpress-deploy#24]
Hey,
I am using MAMP Pro on Yosemite. I have moved the document root folder to Sites.
I am receiving the following error when running the task: `grunt pull_db --target=staging`

Anyone have any ideas on how to resolve this?

Thanks in advance.

```
Pulling database from 'staging' into Local
>> Creating DUMP of remote database
>> Database DUMP succesfully exported to:
>> backups/staging/20141205/21-29-25/db_backup.sql
>> Adapt the database: set the correct urls for the destination in the database.
>> Creating DUMP of local database
>> Database DUMP succesfully exported to:
>> backups/local/20141205/21-29-25/db_backup.sql
>> Importing DUMP into local database
Warning: Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
>> Database imported succesfully

Operations completed
```

**Comment by tomvdv** [comment]
See https://github.com/webrain/grunt-wordpress-deploy/pull/6

**Comment by chriswinch** [comment]
@tomvdv sorry, i'm a bit lost. Can you please explain what i should be looking at in particular from that pull request?

**Comment by tomvdv** [comment]
@chriswinch Check out the "Files changed" tab in the link above. All my pull request does is remove any lines starting with "Warning:" from the SQL dump, which allows the task to complete as expected.

**Comment by chriswinch** [comment]
@tomvdv Thanks for getting back to me.
I have copied your util.js file but still receive the same error:

```
Warning: Using a password on the command line interface can be insecure.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
```

The db is being saved to /backups but is not imported.

**Comment by tomvdv** [comment]
@chriswinch My bad, I stopped reading after the warning message. #6 will still fix that.

`ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/tmp/mysql.sock'` is a local configuration problem: MySQL cannot connect to the database. Is MySQL running? If so, what does your error log have to say?

**Comment by chriswinch** [comment]
@tomvdv Thanks for your help.
Knowing that it was probably a problem with my local setup rather than the plugin itself led me to find this: http://fischerlaender.de/apple-mac/mac-os-x-trouble-with-mamp-mysql

Just had to create a sym link to the correct socket file.
