### ISSUE TITLE
pull_db not working properly

### ISSUE THREAD

**Issue by brianveltman** [webrain/grunt-wordpress-deploy#26]
running pull_db --target=staging returns:

mysqldump: Got error: 1045: "Access denied for user 'wpdeploy'@'ip.of.our.server' (using password: YES)" when trying to connect

staging: {
                "title": "staging",
                "database": "MWPdb",
                "user": "wpdeploy",
                "pass": "somepassword",
                "host": "our.server.com",
                "url": "http://our.server.com",
                "path": "/opt/sites/www/wordpress",
                "ssh_host": "deploy@our.server.com"
            }

But when I run the command:
mysqldump -h our.server.com -u wpdeploy -p MWPdb

It just downloads the SQL. (ofc I entered the password first)

**Comment by stevepiron** [comment]
Same problem. Not sure about that but shouldn't the syntax be user@host instead of 'user'@'host'? Would love this feature to work!
