### ISSUE TITLE
pull_files goes in wrong directory when target path is missing trailing slash

### ISSUE THREAD

**Issue by manolof** [webrain/grunt-wordpress-deploy#40]
I've been trying to pull files from an environment to my local, and the files were not being added to the path that I've set in the local `"path":`.
I've tried debugging it and figured out that if the target path is missing a trailing slash, it creates another folder in the local path directory, named after the target path's basename folder. Here's what I mean:

target path: `"path": "/var/www/target_directory"`
local path: `"path": "/var/www/local_directory"`
would add files in `/var/www/local_directory/target_directory`

Hope that makes sense. It wasn't mentioned in the docs, and the example is also missing the trailing slash.

**Comment by jonmunson** [comment]
I have found a similar issue.

When I _pull_ files, the **local** path needs to be like this:
`"path": "/Users/username/Sites/website-folder"`
and the **remote** path like this:
`"path": "/var/www/website-folder/",`

However, if I _push_ files with this configuration I get this on the remote server:
`/var/www/website/website/`

Currently I am changing the path depending on if I push or pull. If would be useful to have more detail in the documentation, unless I'm missing something?

**Comment by herbie4** [comment]
You always need a closing slash on the path. So you have to correct your local path by adding a '/' at the end.

**Comment by pixelmultiplo** [comment]
Even with both trailing slashes, this still happens.
